CREATE TABLE USERTBL(
NO NUMBER(4) CONSTRAINT PK_USERTBL PRIMARY KEY,
USERNAME VARCHAR2(20) NOT NULL,
BIRTHYEAR NUMBER(4) NOT NULL,
ADDR VARCHAR(20) NOT NULL,
MOBILE VARCHAR(20));

-- NO : 번호(순차적인 번호 부여) => 시퀀스
CREATE SEQUENCE USER_SEQ;

INSERT INTO USERTBL VALUES
(USER_SEQ.NEXTVAL, '홍길동',1985,'서울','010-1234-5678');

COMMIT;

INSERT INTO USERTBL VALUES
(USER_SEQ.NEXTVAL, '김지우',1986,'부산','010-3489-1288');

INSERT INTO USERTBL VALUES
(USER_SEQ.NEXTVAL, '신동완',1990,'경기','010-9084-5458');

SELECT * FROM USERTBL;

UPDATE USERTBL SET ADDR='인천' WHERE NO=1;
DELETE FROM USERTBL WHERE NO=3;

COMMIT;
